import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import puppeteer from "puppeteer";
import { env } from "../env.js";

export interface PrescriptionPdfData {
  clinic: { name: string; brandColor: string | null; address: string | null; phone: string | null };
  doctor: { name: string; specialty: string | null; licenseNo: string | null };
  patient: { firstName: string; lastName: string; mrn: string; gender: string | null; dob: Date | null };
  prescription: { id: string; issuedAt: Date; notes: string | null };
  items: {
    drugName: string;
    dosage: string | null;
    frequency: string | null;
    durationDays: number | null;
    instructions: string | null;
  }[];
}

function esc(value: string | null | undefined): string {
  return (value ?? "").replace(/[&<>"]/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : "&quot;",
  );
}

function age(dob: Date | null): string {
  if (!dob) return "—";
  const diff = Date.now() - new Date(dob).getTime();
  return `${Math.floor(diff / (365.25 * 24 * 3600 * 1000))} yrs`;
}

function template(d: PrescriptionPdfData): string {
  const brand = d.clinic.brandColor || "#2563eb";
  const rows = d.items
    .map(
      (it, i) => `<tr>
        <td class="num">${i + 1}</td>
        <td><strong>${esc(it.drugName)}</strong></td>
        <td>${esc(it.dosage) || "—"}</td>
        <td>${esc(it.frequency) || "—"}</td>
        <td>${it.durationDays ? `${it.durationDays} days` : "—"}</td>
        <td>${esc(it.instructions) || "—"}</td>
      </tr>`,
    )
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8" /><style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; color: #0f172a; margin: 0; }
    .bar { height: 8px; background: ${brand}; }
    .head { display: flex; justify-content: space-between; align-items: flex-start; padding: 24px 0 16px; border-bottom: 1px solid #e2e8f0; }
    .clinic { font-size: 22px; font-weight: 700; color: ${brand}; }
    .muted { color: #64748b; font-size: 12px; }
    .doc { text-align: right; font-size: 13px; }
    .doc .name { font-weight: 700; }
    .patient { display: flex; gap: 32px; margin: 18px 0; font-size: 13px; }
    .patient .label { color: #94a3b8; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; }
    .rx { font-size: 40px; font-weight: 700; color: ${brand}; margin: 8px 0 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 12.5px; }
    th { text-align: left; background: #f1f5f9; color: #475569; padding: 8px 10px; font-size: 11px; text-transform: uppercase; letter-spacing: .03em; }
    td { padding: 9px 10px; border-bottom: 1px solid #eef2f7; vertical-align: top; }
    td.num { color: #94a3b8; width: 24px; }
    .notes { margin-top: 18px; font-size: 12.5px; }
    .notes .label { color: #94a3b8; font-size: 11px; text-transform: uppercase; }
    .sign { margin-top: 56px; text-align: right; font-size: 12px; }
    .sign .line { display: inline-block; width: 200px; border-top: 1px solid #94a3b8; padding-top: 6px; }
    .foot { margin-top: 28px; padding-top: 12px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 10.5px; text-align: center; }
  </style></head><body>
    <div class="bar"></div>
    <div style="padding: 0 40px 40px;">
      <div class="head">
        <div>
          <div class="clinic">${esc(d.clinic.name)}</div>
          <div class="muted">${esc(d.clinic.address) || ""}${d.clinic.phone ? " · " + esc(d.clinic.phone) : ""}</div>
        </div>
        <div class="doc">
          <div class="name">${esc(d.doctor.name)}</div>
          <div class="muted">${esc(d.doctor.specialty) || ""}</div>
          <div class="muted">${d.doctor.licenseNo ? "Lic. " + esc(d.doctor.licenseNo) : ""}</div>
        </div>
      </div>

      <div class="patient">
        <div><div class="label">Patient</div>${esc(d.patient.firstName)} ${esc(d.patient.lastName)}</div>
        <div><div class="label">MRN</div>${esc(d.patient.mrn)}</div>
        <div><div class="label">Gender</div>${esc(d.patient.gender) || "—"}</div>
        <div><div class="label">Age</div>${age(d.patient.dob)}</div>
        <div><div class="label">Date</div>${new Date(d.prescription.issuedAt).toLocaleDateString()}</div>
      </div>

      <div class="rx">℞</div>
      <table>
        <thead><tr><th>#</th><th>Medication</th><th>Dosage</th><th>Frequency</th><th>Duration</th><th>Instructions</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>

      ${d.prescription.notes ? `<div class="notes"><div class="label">Notes</div>${esc(d.prescription.notes)}</div>` : ""}

      <div class="sign"><div class="line">${esc(d.doctor.name)}</div></div>

      <div class="foot">
        This prescription was generated by ClinicFlow — a demo application. Not a certified medical document.
        · Ref ${esc(d.prescription.id)}
      </div>
    </div>
  </body></html>`;
}

/** Render a branded prescription PDF, persist it under STORAGE_DIR, return the bytes + path. */
export async function renderPrescriptionPdf(
  data: PrescriptionPdfData,
): Promise<{ bytes: Buffer; filePath: string }> {
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });
  try {
    const page = await browser.newPage();
    await page.setContent(template(data), { waitUntil: "networkidle0" });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "0mm", bottom: "12mm", left: "0mm", right: "0mm" },
    });
    const relPath = path.join(env.STORAGE_DIR, `prescription-${data.prescription.id}.pdf`);
    const absPath = path.resolve(process.cwd(), relPath);
    mkdirSync(path.dirname(absPath), { recursive: true });
    writeFileSync(absPath, pdf);
    return { bytes: Buffer.from(pdf), filePath: relPath };
  } finally {
    await browser.close();
  }
}
